[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:iventoy]
directory=/iventoy
command=/iventoy/lib/iventoy
environment=IVENTOY_API_ALL="1",IVENTOY_AUTO_RUN="1",LD_LIBRARY_PATH="/iventoy/lib/lin64"
autostart=true
autorestart=true
startretries=5
stderr_logfile=/var/log/supervisor/iventoy.err.log
stdout_logfile=/var/log/supervisor/iventoy.out.log
